#!/usr/bin/python3
#	jbin - Joe's miscellaneous scripts, tools and configs
#	audiocat: Concatenate audio files
#	Copyright (C) 2025-2025 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
import os
import tempfile
import subprocess
from FriendlyArgumentParser import FriendlyArgumentParser

parser = FriendlyArgumentParser(description = "Concatenate audio data.")
parser.add_argument("-o", "--output-filename", metavar = "file", default = "audiocat-output.mp3", help = "Resulting output file. Defaults to %(default)s.")
parser.add_argument("-v", "--verbose", action = "count", default = 0, help = "Increases verbosity. Can be specified multiple times to increase.")
parser.add_argument("filename", nargs = "+", help = "Use these audio file(s) as input")
args = parser.parse_args(sys.argv[1:])

if args.verbose:
	for filename in args.filename:
		print(filename)

with tempfile.NamedTemporaryFile(mode = "w", prefix = "audiocat_", suffix = ".txt") as f:
	for filename in args.filename:
		print(f"file '{os.path.realpath(filename)}'", file = f)
	f.flush()
	subprocess.check_call([ "ffmpeg", "-f", "concat", "-safe", "0", "-i", f"{f.name}", "-c", "copy", args.output_filename ])
