#!/usr/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	delaytype: Type the clipboard after a few seconds
#	Copyright (C) 2022-2023 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

if [ "$1" == "" ]; then
	DELAY_SECS="2"
else
	DELAY_SECS="$1"
fi
if [ "$2" == "" ]; then
	TEXT=`xclip -o`
	if [ "$TEXT" == "" ]; then
		echo "Refusing to type empty clipboard."
		exit 1
	fi
else
	TEXT="$2"
fi

echo "Typing \"${TEXT}\" in ${DELAY_SECS} seconds..."
sleep "$DELAY_SECS"
xdotool type "$TEXT"
