#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	dmesg_log: Repeatedly call dmesg, put timestamps on the log and write to file
#	Copyright (C) 2009-2018 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

LOGFILE="${1}"
TEMPFILE="${1}_dmesg.tmp"
if [ "$LOGFILE" != "" ] && [ -f "${LOGFILE}" ]; then
	echo "${LOGFILE} exists."
	exit 1
fi

if [ "$LOGFILE" == "" ]; then
	echo "Will not log to file."
fi

if [ -f "${TEMPFILE}" ]; then
	echo "${TEMPFILE} exists."
	exit 1
fi

while true; do
	dmesg -c > "${TEMPFILE}"
	lines=`wc -l < "${TEMPFILE}"`
	if [ "$lines" != "0" ]; then
		datum=`/bin/date +'%Y-%m-%d %H:%M:%S'`
		cat "${TEMPFILE}" | awk '{print "'"${datum}"' " $0}'
		if [ "$LOGFILE" != "" ]; then
			cat "${TEMPFILE}" | awk '{print "'"${datum}"' " $0}' >> "${LOGFILE}"
		fi
	fi
	rm -f "${TEMPFILE}"
	sleep 1
done
