#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	dmesg_log: Repeatedly call dmesg, put timestamps on the log and write to file
#	Copyright (C) 2009-2018 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

LOGFILE="${1}"
TEMPFILE="${1}_dmesg.tmp"

if [ -f "${TEMPFILE}" ]; then
	echo "Temporary file ${TEMPFILE} exists, remove before logging to file."
	exit 1
fi

if [ "$LOGFILE" != "" ] && [ -f "${LOGFILE}" ]; then
	read -p "${TEMPFILE} exists, append (y/n)? " yn
	if [ "$yn" != "y" ] && [ "$yn" != "Y" ]; then
		echo "Aborting."
		exit 1
	fi
fi

if [ "$LOGFILE" == "" ]; then
	echo "Will not log to file."
else
	echo "Will log to file: ${LOGFILE}"
fi

while true; do
	dmesg -c >"${TEMPFILE}"
	lines=`wc -l <"${TEMPFILE}"`
	if [ "$lines" != "0" ]; then
		TIMESTAMP=`/bin/date +'%Y-%m-%d %H:%M:%S'`
		cat "${TEMPFILE}" | awk '{print "'"${TIMESTAMP}"' " $0}'
		if [ "$LOGFILE" != "" ]; then
			cat "${TEMPFILE}" | awk '{print "'"${TIMESTAMP}"' " $0}' >>"${LOGFILE}"
			sync
		fi
	fi
	rm -f "${TEMPFILE}"
	sleep 1
done
