#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	git-clone-cwd: Clone a remote repository so that it appears within the cwd
#	Copyright (C) 2019-2019 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>


GITREPO="$1"
TEMPDIR="__gitclone_tmpdir"
if [ "$1" == "" ]; then
	echo "$0 [git repository]"
	exit 1
fi

if [ -d ".git" ]; then
	echo "Git directory .git already exists."
	exit 1
fi

if [ -d "$TEMPDIR" ]; then
	echo "Already exists: $TEMPDIR"
	exit 1
fi

git clone "$GITREPO" "$TEMPDIR"
mv "${TEMPDIR}/.git" .
rm -fr "$TEMPDIR"
git checkout .
