#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	git-change-email: Call "git filter-branch" and change email address from X to Y
#	Copyright (C) 2018-2018 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

if [ "$#" != "2" ]; then
	echo "$0 [old email] [new email]"
	exit 1
fi

OLD_EMAIL="$1"
NEW_EMAIL="$2"

git filter-branch --env-filter '
    if test "$GIT_AUTHOR_EMAIL" = "'${OLD_EMAIL}'"
    then
        GIT_AUTHOR_EMAIL="'${NEW_EMAIL}'"
    fi
    if test "$GIT_COMMITTER_EMAIL" = "'${OLD_EMAIL}'"
    then
        GIT_COMMITTER_EMAIL="'${NEW_EMAIL}'"
    fi
' -- --all
