#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	git-clean-submodules: Cleans up and updates git repos, including submodules
#	Copyright (C) 2020-2020 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

CLEAN_PARAM="$1"
if [ "$CLEAN_PARAM" == "" ]; then
	echo "$0 [clean parameter]"
	echo "e.g., $0 -dfx"
	exit 1
fi

git clean "$CLEAN_PARAM"
git submodule foreach --recursive git clean "$CLEAN_PARAM"
git reset --hard
git submodule foreach --recursive git reset --hard
git submodule update --init --recursive
