#!/bin/bash -e
#	jbin - Joe's miscellaneous scripts, tools and configs
#	git-patches: Create a .tar.gz file that contains all patches on top of master
#	Copyright (C) 2015-2018 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

DATE=`/bin/date +'%Y_%m_%d_%H_%M_%S'`

REMOTE=`git config --get remote.origin.url`
if [ "$REMOTE" == "" ]; then
	OUTDIR="patches_${DATE}"
else
	REMOTE=`basename "$REMOTE"`
	if [ "${REMOTE:$((${#REMOTE}-4))}" == ".git" ]; then
		REMOTE="${REMOTE:0:$((${#REMOTE}-4))}"
	fi
	OUTDIR="${REMOTE}_patches_${DATE}"
fi
OUTFILE="${OUTDIR}.tar.gz"

if [ -d "${OUTFILE}" ]; then
	echo "Will not overwrite output directory ${OUTDIR}."
	exit 1
fi
if [ -f "${OUTFILE}" ]; then
	echo "Will not overwrite output file ${OUTFILE}."
	exit 1
fi

if [ "$1" != "" ]; then
	PATCH_BASE="$1"
else
	BASE_BRANCH=`git show-branch -a | grep '^\*\s*+' | head -n1 | sed 's/.*\[\([^]]\+\)\].*/\1/g;'`
	if [ "$BASE_BRANCH" == "" ]; then
		PATCH_BASE="origin/master"
	else
		PATCH_BASE="origin/${BASE_BRANCH}"
	fi
fi

mkdir "$OUTDIR"
git format-patch -o "$OUTDIR" "$PATCH_BASE" >/dev/null 2>&1
echo "$PATCH_BASE" >"${OUTDIR}/PATCHBASE"
git rev-parse "$PATCH_BASE" >>"${OUTDIR}/PATCHBASE"
tar cfvz "$OUTFILE" "$OUTDIR"
rm -fr "$OUTDIR"
