#!/usr/bin/python3
#	jbin - Joe's miscellaneous scripts, tools and configs
#	jsonlint: Pretty-print JSON data
#	Copyright (C) 2019-2025 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import json
import os
import sys
import collections
from FriendlyArgumentParser import FriendlyArgumentParser

class JSONLinter():
	def __init__(self, args):
		self._args = args

	def _lint_data(self, bytes_data: bytes):
		data = json.loads(bytes_data, object_pairs_hook = collections.OrderedDict)
		if self._args.output_format == "pretty":
			return json.dumps(data, indent = 4 if self._args.use_spaces else "\t", sort_keys = self._args.sort_keys == "alphabetical", ensure_ascii = not self._args.allow_unicode)
		elif self._args.output_format == "oneline":
			return json.dumps(data, sort_keys = self._args.sort_keys == "alphabetical", ensure_ascii = not self._args.allow_unicode)
		elif self._args.output_format == "brief":
			return json.dumps(data, separators = (",", ":"), sort_keys = self._args.sort_keys == "alphabetical", ensure_ascii = not self._args.allow_unicode)
		else:
			raise NotImplementedError(self._args.output_format)

	def _lint_file(self, filename: str):
		with open(filename, "rb") as f:
			data = f.read()
		result = self._lint_data(data)
		if self._args.in_place:
			# Modify the file in-place
			temp_json_filename = f"{filename}_jsonlint"
			if os.path.isfile(temp_json_filename):
				print(f"Refusing to overwrite temporary file: {temp_json_filename}, {filename} was not modified.", file = sys.stderr)
				return

			with open(temp_json_filename, "w") as f:
				print(result, file = f)

			# Atomically replace file
			try:
				os.rename(temp_json_filename, filename)
			except:
				os.unlink(temp_json_filename)
		else:
			# Just print output
			print(result)

	def run(self):
		if len(self._args.filename) == 0:
			# Read from stdin
			if self._args.in_place:
				print("Cannot modify stdin in-place, incompatible options.", file = sys.stderr)
				return 1
			self._lint_data(sys.stdin.read())
		else:
			# Lint files
			for filename in self._args.filename:
				self._lint_file(filename)
		return 0

parser = FriendlyArgumentParser(description = "Format a JSON file nicely.")
parser.add_argument("-i", "--in-place", action = "store_true", help = "Modify files in-place, i.e., write the result back to the file.")
parser.add_argument("-u", "--allow-unicode", action = "store_true", help = "Do not force ASCII-only output, but allow unicode characters as well.")
parser.add_argument("-S", "--use-spaces", action = "store_true", help = "Use spaces instead of tabs for indentation. Only has an effect when the 'pretty' output format is chosen.")
parser.add_argument("-s", "--sort-keys", choices = [ "alphabetical", "keep" ], default = "keep", help = "Sort the keys of dicts in the described fashion. Can be one of %(choices)s, defaults to %(default)s.")
parser.add_argument("-o", "--output-format", choices = [ "pretty", "oneline", "brief" ], default = "pretty", help = "Show the output in the described fashion. Can be one of %(choices)s, defaults to %(default)s.")
parser.add_argument("filename", metavar = "filename", nargs = "*", help = "Lint these filename(s). If omitted, read from stdin.")
args = parser.parse_args(sys.argv[1:])

sys.exit(JSONLinter(args).run())
