#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	ssh-show-local-fingerprints: Show server's SSH fingerprints locally
#	Copyright (C) 2014-2018 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>


for METHOD in rsa dsa ecdsa ed25519; do
	PUBKEY="/etc/ssh/ssh_host_${METHOD}_key.pub"
	if [ ! -f "$PUBKEY" ]; then
		continue
	fi
	ssh-keygen -l -f "$PUBKEY"
done
