#!/usr/bin/python3
#	jbin - Joe's miscellaneous scripts, tools and configs
#	stopwatch: Show a command-line timer
#	Copyright (C) 2022-2024 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import time
import datetime
import sys
import signal
import subprocess
from FriendlyArgumentParser import FriendlyArgumentParser

class StopWatch():
	def __init__(self, args):
		self._args = args
		self._t0 = time.time()
		self._tsum = 0
		self._notifications = [ ]
		for value in self._args.sound:
			if not self._args.notification_secs:
				value *= 60
			self._notifications.append(value)
		self._notifications.sort()

	@property
	def seconds(self):
		if self._t0 is not None:
			return round(time.time() - self._t0 + self._tsum)
		else:
			return round(self._tsum)

	@property
	def stopped(self):
		return self._t0 is None

	def _start(self):
		self._t0 = time.time()

	def _stop(self):
		self._tsum += time.time() - self._t0
		self._t0 = None

	@staticmethod
	def _fmt_now():
		return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

	@staticmethod
	def _fmt_secs(secs):
		if secs < 3600:
			return f"{secs // 60}:{secs % 60:02d}"
		else:
			return f"{secs // 3600}:{secs % 3600 // 60:02d}:{secs % 3600 % 60:02d}"


	@staticmethod
	def _input_timeout(prompt, timeout_secs):
		class TimeExpiredException(Exception): pass

		def raise_exception(signum, frame):
			raise TimeExpiredException()

		try:
			signal.signal(signal.SIGALRM, raise_exception)
			signal.alarm(timeout_secs)
			result = input(prompt)
			signal.alarm(0)
		except TimeExpiredException:
			result = None
		return result

	def _play_notification(self):
		subprocess.Popen([ "mpv", self._args.notification_sound ], stdout = subprocess.DEVNULL, stderr = subprocess.DEVNULL)

	def _notify(self):
		now = self.seconds
		while len(self._notifications) > 0:
			next_at = self._notifications[0]
			if now >= next_at:
				# Notify!
				self._notifications.pop(0)
				self._play_notification()
			else:
				break

	def run(self):
		clr = "\r\033[K"

		print(f"Start time: {self._fmt_now()}")
		try:
			while True:
				cmd = self._input_timeout(f"{clr}{self._fmt_secs(self.seconds)} {'stopped' if self.stopped else ''}", timeout_secs = 1)
				self._notify()
				if cmd == "":
					if not self.stopped:
						print(f"Intermediate time: {self._fmt_now()} -- time taken {self._fmt_secs(self.seconds)}")
				elif cmd == "s":
					if not self.stopped:
						# Stopping
						print(f"Stopped at: {self._fmt_now()} -- time taken {self._fmt_secs(self.seconds)}")
						self._stop()
					else:
						# Starting
						print(f"Restarted at: {self._fmt_now()} -- time taken {self._fmt_secs(self.seconds)}")
						self._start()

		except KeyboardInterrupt:
			pass
		finally:
			print()
			print(f"End time: {self._fmt_now()} -- time taken {self._fmt_secs(self.seconds)}")

parser = FriendlyArgumentParser(description = "Command line stopwatch.")
parser.add_argument("--notification-secs", action = "store_true", help = "Instead of minutes, use seconds for the notification command line option.")
parser.add_argument("-s", "--sound", metavar = "minutes", type = int, action = "append", default = [ ], help = "Play a notification sound at this minute mark. Can be used multiple times.")
parser.add_argument("-n", "--notification-sound", metavar = "file", default = "/usr/share/sounds/freedesktop/stereo/complete.oga", help = "Notification sound to play when mark is hit. Defaults to %(default)s.")
args = parser.parse_args(sys.argv[1:])

StopWatch(args).run()
