#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	vi : Call vim or gvim depending on the availability
#	Copyright (C) 2009-2018 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

if [ "$DISPLAY" == "" ]; then
	exec vim "$@"
else
	which gvim >/dev/null 2>&1
	havegvim="$?"
	if [ "$havegvim" != "0" ]; then
		exec vim "$@"
	else
		# Open GVim in full screen mode. Check resolution first to determine
		# font size to use
		SCREEN_HEIGHT=`xwininfo -root | grep Height | awk '{print $2}'`
		if [ "$SCREEN_HEIGHT" -gt "1200" ]; then
			# This is probably a 4K monitor
			exec gvim -geometry 1000x1000 -c 'set guifont=Latin\ Modern\ Mono\ 18' "$@" >/dev/null 2>&1
		else
			exec gvim -geometry 1000x1000 "$@" >/dev/null 2>&1
		fi
	fi
fi
