#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	wifi-gen-qrcode: generate a QR code that contains WiFi credentials
#	Copyright (C) 2015-2018 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

read -p "ESSID   : " ESSID
read -p "Password: " PASSWD
QRSTR="WIFI:S:${ESSID};T:WPA;P:${PASSWD};;"

outfile="wifi_${ESSID}.svg"
qrencode -t SVG -o "$outfile" -l m "$QRSTR"
echo "written: $outfile"
