#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	import_dconf: Import all dconf configuration
#	Copyright (C) 2018-2018 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

for DCONF_FILE in /usr/jbin/conf/dconf/*; do
	if [ ! -f "$DCONF_FILE" ]; then
		continue
	fi
	echo "`basename $DCONF_FILE`"
	dconf load / <"$DCONF_FILE"
done
