#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	boot_windows: Boots into the grub "Windows" entry
#	Copyright (C) 2018-2018 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

OS=`grep -E "^menuentry 'Windows" /boot/grub/grub.cfg | head -n1 | awk -F "'" '{print $2}'`
if [ "$OS" == "" ]; then
	echo "Unable to determine boot entry."
	exit 1
fi

read -p "Boot to ${OS}? Press ENTER to continue..." x
grub-reboot "$OS"
reboot
