#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	dkms_rebuild: Rebuild all DKMS kernel modules for a particular kernel version
#	Copyright (C) 2019-2021 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

VERBOSE="0"
KERNEL_VERSION=""
while [ "$1" != "" ]; do
	if [ "$1" == "-v" ]; then
		VERBOSE="1"
	elif [ "$1" == "--help" ]; then
		echo "$0 [-v] (kernel version])"
		exit 1
	else
		KERNEL_VERSION="$1"
	fi
	shift
done

if [ "$KERNEL_VERSION" == "" ]; then
	KERNEL_VERSION=`uname -r`
	if [ "$VERBOSE" == "1" ]; then
		echo "Building for currently running kernel: ${KERNEL_VERSION}"
	fi
fi


if [ -d "/var/lib/dkms" ]; then
	find /var/lib/dkms -mindepth 2 -maxdepth 2 -type d | cut -c 15- | while read DKMS_MODULE_VERSION; do
		DKMS_MODULE=`echo "$DKMS_MODULE_VERSION" | awk -F '/' '{print $1}'`
		DKMS_VERSION=`echo "$DKMS_MODULE_VERSION" | awk -F '/' '{print $2}'`
		echo "Found DKMS module ${DKMS_MODULE} in module version ${DKMS_VERSION}, trying to build for kernel ${KERNEL_VERSION}"
		dkms remove "${DKMS_MODULE}/${DKMS_VERSION}" -k "${KERNEL_VERSION}"
		if [ "$VERBOSE" == "1" ]; then
			echo "dkms build -m \"${DKMS_MODULE}/${DKMS_VERSION}\" -k \"${KERNEL_VERSION}\""
		fi
		dkms build -m "${DKMS_MODULE}/${DKMS_VERSION}" -k "${KERNEL_VERSION}"
		dkms install -m "${DKMS_MODULE}/${DKMS_VERSION}" -k "${KERNEL_VERSION}"
	done
else
	echo "DKMS directory doesn't exist, skipping building DKMS modules."
fi
