#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	kernel_build: Historize kernel config in git, then build it
#	Copyright (C) 2015-2018 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

KERNDIR="/usr/src/linux"
CONFDIR="/usr/src/kernconfig"
CPUCNT=`cat /proc/cpuinfo | grep "processor" | wc -l`
	
if [ ! -d "$KERNDIR" ]; then
	echo "Kernel directory $KERNDIR not found."
	exit 1
fi

KERNEL_VERSION=`cat ${KERNDIR}/.config | grep "Kernel Configuration" | awk '{print $3}'`

if [ -d "$CONFDIR" ]; then
	CONFFILE="${CONFDIR}/${HOSTNAME}-${KERNEL_VERSION}"
	cd "$CONFDIR"
	cp "${KERNDIR}/.config" "$CONFFILE"
	git add "$CONFFILE"
	git commit "$CONFFILE"
else
	echo "Configuration directory ${CONFDIR} does not exist, kernel config will not be historized."
fi

cd "$KERNDIR"
make bzImage -j${CPUCNT}
make modules -j${CPUCNT}
make modules_install
make install

dkms_rebuild "$KERNEL_VERSION"
