#!/bin/bash
#	jbin - Joe's miscellaneous scripts, tools and configs
#	scsi_rescan: Rescan SCSI bus for hotplugged devices
#	Copyright (C) 2013-2018 Johannes Bauer
#
#	This file is part of jbin.
#
#	jbin is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	jbin is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with jbin. If not, see <http://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

for HOST in /sys/class/scsi_host/*; do
	if [ ! -d "$HOST" ]; then
		continue
	fi
	SCANFILE="${HOST}/scan"
	if [ ! -f "$SCANFILE" ]; then
		continue
	fi
	echo "Scanning $HOST"
	echo "- - -" >"$SCANFILE"
done
